---

- name: Install source
  shell:  |
    curl -O -L https://github.com/prometheus/prometheus/releases/download/v2.47.1/prometheus-2.47.1.linux-amd64.tar.gz
    ls -la
  register: test

- debug:
    var: test.stdout_lines


- name: Unzip source
  become: yes
  shell:  |
    tar -xzf prometheus-2.47.1.linux-amd64.tar.gz
    mkdir -p /usr/local/prometheus-file
    mv prometheus-2.47.1.linux-amd64/* /usr/local/prometheus-file
    mkdir -p /usr/local/prometheus-file/db
    chown -R prometheus:127 /usr/local/prometheus-file/db

- name: Change systemd process
  become: yes
  copy:
    src: prometheus.service
    dest: /etc/systemd/system/prometheus.service


- name: reload prometheus service
  become: yes
  shell:  |
    systemctl daemon-reload
    systemctl start prometheus
    systemctl enable prometheus
    systemctl status prometheus
